/*
 * easypaisa_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package oauthauthorization_pkg

import "easypaisa_lib/models_pkg"
import "easypaisa_lib/configuration_pkg"

/*
 * Interface for the OAUTHAUTHORIZATION_IMPL
 */
type OAUTHAUTHORIZATION interface {
    CreateRequestToken (string, *string, map[string]interface{}) (*models_pkg.OAuthToken, error)
}

/*
 * Factory for the OAUTHAUTHORIZATION interaface returning OAUTHAUTHORIZATION_IMPL
 */
func NewOAUTHAUTHORIZATION(config configuration_pkg.CONFIGURATION) *OAUTHAUTHORIZATION_IMPL {
    client := new(OAUTHAUTHORIZATION_IMPL)
    client.config = config
    return client
}