/*
 * easypaisa_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

package models_pkg



/*
 * Structure for the custom type MerchantPaymentRequest
 */
type MerchantPaymentRequest struct {
    Amount                                     string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency                                   string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type                                       string          `json:"type" form:"type"` //TODO: Write general description for this field
    SubType                                    string          `json:"subType" form:"subType"` //TODO: Write general description for this field
    RequestDate                                string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    DebitParty                                 []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty                                []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    SenderKyc                                  SenderKyc2      `json:"senderKyc" form:"senderKyc"` //TODO: Write general description for this field
    RequestingOrganisationTransactionReference string          `json:"requestingOrganisationTransactionReference" form:"requestingOrganisationTransactionReference"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SenderKyc2
 */
type SenderKyc2 struct {
    EmailAddress    string          `json:"emailAddress" form:"emailAddress"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SendMoneyToMobileAccountRequest
 */
type SendMoneyToMobileAccountRequest struct {
    Amount          string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type            string          `json:"type" form:"type"` //TODO: Write general description for this field
    SubType         string          `json:"subType" form:"subType"` //TODO: Write general description for this field
    RequestDate     string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    DebitParty      []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty     []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    SenderKyc       SenderKyc       `json:"senderKyc" form:"senderKyc"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type DebitParty
 */
type DebitParty struct {
    Key             string          `json:"key" form:"key"` //TODO: Write general description for this field
    Value           string          `json:"value" form:"value"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreditParty
 */
type CreditParty struct {
    Key             string          `json:"key" form:"key"` //TODO: Write general description for this field
    Value           string          `json:"value" form:"value"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SenderKyc
 */
type SenderKyc struct {
    IdDocument      []*IdDocument   `json:"idDocument" form:"idDocument"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type IdDocument
 */
type IdDocument struct {
    IdType          string          `json:"idType" form:"idType"` //TODO: Write general description for this field
    IdNumber        string          `json:"idNumber" form:"idNumber"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SendMoneyToMobileAccountResponse
 */
type SendMoneyToMobileAccountResponse struct {
    Amount          string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type            string          `json:"type" form:"type"` //TODO: Write general description for this field
    SubType         string          `json:"subType" form:"subType"` //TODO: Write general description for this field
    RequestDate     string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    DebitParty      []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty     []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    Metadata        []*Metadatum    `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MoneyTransferToBankRequest
 */
type MoneyTransferToBankRequest struct {
    Amount          string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type            string          `json:"type" form:"type"` //TODO: Write general description for this field
    SubType         string          `json:"subType" form:"subType"` //TODO: Write general description for this field
    RequestDate     string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    DebitParty      []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty     []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    SenderKyc       SenderKyc1      `json:"senderKyc" form:"senderKyc"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SenderKyc1
 */
type SenderKyc1 struct {
    Name            string          `json:"Name" form:"Name"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MoneyTransferToBankResponse
 */
type MoneyTransferToBankResponse struct {
    Amount               string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type                 string          `json:"type" form:"type"` //TODO: Write general description for this field
    TransactionStatus    string          `json:"transactionStatus" form:"transactionStatus"` //TODO: Write general description for this field
    RequestDate          string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    TransactionReference string          `json:"transactionReference" form:"transactionReference"` //TODO: Write general description for this field
    DebitParty           []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty          []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    Metadata             []*Metadatum    `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Metadatum
 */
type Metadatum struct {
    Key             string          `json:"key" form:"key"` //TODO: Write general description for this field
    Value           string          `json:"value" form:"value"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MoneyTransferToMobileAccountRequest
 */
type MoneyTransferToMobileAccountRequest struct {
    Amount          string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type            string          `json:"type" form:"type"` //TODO: Write general description for this field
    SubType         string          `json:"subType" form:"subType"` //TODO: Write general description for this field
    RequestDate     string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    DebitParty      []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty     []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    SenderKyc       SenderKyc1      `json:"senderKyc" form:"senderKyc"` //TODO: Write general description for this field
    RecipientKyc    RecipientKyc    `json:"recipientKyc" form:"recipientKyc"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type RecipientKyc
 */
type RecipientKyc struct {
    Name            string          `json:"Name" form:"Name"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MoneyTransferToMobileAccountResponse
 */
type MoneyTransferToMobileAccountResponse struct {
    Amount               string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type                 string          `json:"type" form:"type"` //TODO: Write general description for this field
    TransactionStatus    string          `json:"transactionStatus" form:"transactionStatus"` //TODO: Write general description for this field
    RequestDate          string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    TransactionReference string          `json:"transactionReference" form:"transactionReference"` //TODO: Write general description for this field
    DebitParty           []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty          []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
    Metadata             []*Metadatum    `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type BillPaymentRequest
 */
type BillPaymentRequest struct {
    Currency                          string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    PaidAmount                        string          `json:"paidAmount" form:"paidAmount"` //TODO: Write general description for this field
    SupplementaryBillReferenceDetails []*SupplementaryBillReferenceDetail `json:"supplementaryBillReferenceDetails" form:"supplementaryBillReferenceDetails"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SupplementaryBillReferenceDetail
 */
type SupplementaryBillReferenceDetail struct {
    PaymentReferenceType  string          `json:"paymentReferenceType" form:"paymentReferenceType"` //TODO: Write general description for this field
    PaymentReferenceValue string          `json:"paymentReferenceValue" form:"paymentReferenceValue"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type BillPaymentResponse
 */
type BillPaymentResponse struct {
    Currency                          string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    PaidAmount                        string          `json:"paidAmount" form:"paidAmount"` //TODO: Write general description for this field
    CustomerReference                 string          `json:"customerReference" form:"customerReference"` //TODO: Write general description for this field
    SupplementaryBillReferenceDetails []*SupplementaryBillReferenceDetail `json:"supplementaryBillReferenceDetails" form:"supplementaryBillReferenceDetails"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type ErrorParameter
 */
type ErrorParameter struct {
    Key             string          `json:"key" form:"key"` //TODO: Write general description for this field
    Value           string          `json:"value" form:"value"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type BillInquiryResponse
 */
type BillInquiryResponse struct {
    Currency        string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    AmountDue       string          `json:"amountDue" form:"amountDue"` //TODO: Write general description for this field
    DueDate         string          `json:"dueDate" form:"dueDate"` //TODO: Write general description for this field
    BillStatus      string          `json:"billStatus" form:"billStatus"` //TODO: Write general description for this field
    Metadata        []*Metadatum    `json:"metadata" form:"metadata"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetCompanyListResponse
 */
type GetCompanyListResponse struct {
    Companies       []*Company      `json:"companies" form:"companies"` //TODO: Write general description for this field
    Description     string          `json:"description" form:"description"` //TODO: Write general description for this field
    ResultCode      string          `json:"resultCode" form:"resultCode"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type Company
 */
type Company struct {
    CompanyName      string          `json:"company_name" form:"company_name"` //TODO: Write general description for this field
    ServiceProvider  string          `json:"service_provider" form:"service_provider"` //TODO: Write general description for this field
    SubType          string          `json:"sub_type" form:"sub_type"` //TODO: Write general description for this field
    Type             string          `json:"type" form:"type"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MerchantPaymentResponse
 */
type MerchantPaymentResponse struct {
    Amount               string          `json:"amount" form:"amount"` //TODO: Write general description for this field
    Currency             string          `json:"currency" form:"currency"` //TODO: Write general description for this field
    Type                 string          `json:"type" form:"type"` //TODO: Write general description for this field
    TransactionStatus    string          `json:"transactionStatus" form:"transactionStatus"` //TODO: Write general description for this field
    RequestDate          string          `json:"requestDate" form:"requestDate"` //TODO: Write general description for this field
    TransactionReference string          `json:"transactionReference" form:"transactionReference"` //TODO: Write general description for this field
    DebitParty           []*DebitParty   `json:"debitParty" form:"debitParty"` //TODO: Write general description for this field
    CreditParty          []*CreditParty  `json:"creditParty" form:"creditParty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type OAuthToken
 */
type OAuthToken struct {
    AccessToken     string          `json:"access_token" form:"access_token"` //Access token
    TokenType       string          `json:"token_type" form:"token_type"` //Type of access token
    ExpiresIn       *int64          `json:"expires_in,omitempty" form:"expires_in,omitempty"` //Time in seconds before the access token expires
    Scope           *string         `json:"scope,omitempty" form:"scope,omitempty"` //List of scopes granted
    Expiry          *int64          `json:"expiry,omitempty" form:"expiry,omitempty"` //Time of token expiry as unix timestamp (UTC)
}
